# Generated by Django 5.2.6 on 2025-11-01 13:53

import api.models
import api.validators
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="UserAccount",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "username",
                    models.CharField(
                        max_length=150, unique=True, verbose_name="Tên đăng nhập"
                    ),
                ),
                (
                    "password",
                    models.CharField(max_length=128, verbose_name="Mật khẩu (đã băm)"),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True, max_length=254, null=True, unique=True
                    ),
                ),
                ("first_name", models.CharField(max_length=150, verbose_name="Tên")),
                ("last_name", models.CharField(max_length=150, verbose_name="Họ")),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Đang hoạt động"),
                ),
                (
                    "is_superuser",
                    models.BooleanField(
                        default=False, verbose_name="Là Quản trị viên tối cao"
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("ADMIN", "Quản trị viên"),
                            ("DOCTOR", "Bác sĩ"),
                            ("RECEPTIONIST", "Lễ tân"),
                            ("PATIENT", "Bệnh nhân"),
                        ],
                        max_length=50,
                        verbose_name="Vai trò trên App",
                    ),
                ),
                (
                    "phone_number",
                    models.CharField(
                        blank=True,
                        max_length=11,
                        null=True,
                        unique=True,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Số điện thoại phải có định dạng đúng (10-11 chữ số).",
                                regex="^\\d{10,11}$",
                            )
                        ],
                        verbose_name="Số điện thoại",
                    ),
                ),
                (
                    "avatar",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="avatars/",
                        verbose_name="Ảnh đại diện",
                    ),
                ),
                (
                    "date_of_birth",
                    models.DateField(
                        blank=True,
                        null=True,
                        validators=[api.validators.validate_no_future_date],
                        verbose_name="Ngày sinh",
                    ),
                ),
                (
                    "address",
                    models.CharField(max_length=255, null=True, verbose_name="Địa chỉ"),
                ),
                (
                    "gender",
                    models.CharField(
                        blank=True,
                        choices=[("MALE", "Nam"), ("FEMALE", "Nữ"), ("OTHER", "Khác")],
                        max_length=10,
                        null=True,
                        verbose_name="Giới tính",
                    ),
                ),
                (
                    "date_joined",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="Ngày tham gia"
                    ),
                ),
                ("is_staff", models.BooleanField(default=False)),
            ],
            options={
                "verbose_name": "1. Tài khoản Người dùng (Tùy chỉnh)",
                "verbose_name_plural": "1. Các Tài khoản Người dùng (Tùy chỉnh)",
            },
            managers=[
                ("objects", api.models.UserAccountManager()),
            ],
        ),
        migrations.CreateModel(
            name="Medicine",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=100, unique=True, verbose_name="Tên thuốc"
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, null=True, verbose_name="Mô tả"),
                ),
                (
                    "unit",
                    models.CharField(
                        default="Viên", max_length=20, verbose_name="Đơn vị tính"
                    ),
                ),
                (
                    "stock_quantity",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Số lượng trong kho"
                    ),
                ),
            ],
            options={
                "verbose_name": "Danh mục Thuốc",
                "verbose_name_plural": "Danh mục Thuốc",
            },
        ),
        migrations.CreateModel(
            name="Specialty",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=100, unique=True, verbose_name="Tên chuyên khoa"
                    ),
                ),
            ],
            options={
                "verbose_name": "5. Danh mục Chuyên khoa",
                "verbose_name_plural": "5. Các Danh mục Chuyên khoa",
            },
        ),
        migrations.CreateModel(
            name="PatientProfile",
            fields=[
                (
                    "user",
                    models.OneToOneField(
                        limit_choices_to={"role": "PATIENT"},
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        related_name="patient_profile",
                        serialize=False,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "medical_history",
                    models.TextField(
                        blank=True, null=True, verbose_name="Tiền sử bệnh án"
                    ),
                ),
                (
                    "allergies",
                    models.TextField(blank=True, null=True, verbose_name="Dị ứng"),
                ),
            ],
            options={
                "verbose_name": "2. Hồ sơ Y tế Bệnh nhân",
                "verbose_name_plural": "2. Các hồ sơ Y tế Bệnh nhân",
            },
        ),
        migrations.CreateModel(
            name="ReceptionistProfile",
            fields=[
                (
                    "user",
                    models.OneToOneField(
                        limit_choices_to={"role": "RECEPTIONIST"},
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        related_name="receptionist_profile",
                        serialize=False,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "employee_id",
                    models.CharField(
                        max_length=20, unique=True, verbose_name="Mã nhân viên"
                    ),
                ),
                (
                    "start_date",
                    models.DateField(
                        default=django.utils.timezone.now,
                        verbose_name="Ngày bắt đầu làm việc",
                    ),
                ),
            ],
            options={
                "verbose_name": "4. Hồ sơ Lễ tân",
                "verbose_name_plural": "4. Các hồ sơ Lễ tân",
            },
        ),
        migrations.CreateModel(
            name="Appointment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "appointment_time",
                    models.DateTimeField(verbose_name="Thời gian hẹn"),
                ),
                ("reason", models.TextField(verbose_name="Lý do khám")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PATIENT_REQUESTED", "Chờ Lễ tân xác nhận"),
                            ("RECEPTIONIST_PROPOSED", "Chờ Bệnh nhân xác nhận"),
                            ("CONFIRMED", "Đã xác nhận"),
                            ("CHECKED_IN", "Đã check-in"),
                            ("COMPLETED", "Đã hoàn thành khám"),
                            ("CANCELLED", "Đã hủy"),
                            ("REJECTED", "Đã từ chối"),
                        ],
                        default="PATIENT_REQUESTED",
                        max_length=30,
                    ),
                ),
                (
                    "patient_confirmed_at",
                    models.DateTimeField(
                        blank=True,
                        null=True,
                        verbose_name="Thời điểm Bệnh nhân xác nhận",
                    ),
                ),
                (
                    "reception_notes",
                    models.TextField(
                        blank=True, null=True, verbose_name="Ghi chú của Lễ tân"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_appointments",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Người khởi tạo",
                    ),
                ),
                (
                    "doctor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="doctor_appointments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="patient_appointments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "receptionist_confirmed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="confirmed_appointments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "8. Lịch hẹn",
                "verbose_name_plural": "8. Các Lịch hẹn",
                "ordering": ["-appointment_time"],
            },
        ),
        migrations.CreateModel(
            name="Encounter",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("symptoms", models.TextField(verbose_name="Triệu chứng")),
                ("diagnosis", models.TextField(verbose_name="Chẩn đoán")),
                (
                    "appointment",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="api.appointment",
                        verbose_name="Thuộc cuộc hẹn",
                    ),
                ),
            ],
            options={
                "verbose_name": "9. Bệnh án (Lần khám)",
                "verbose_name_plural": "9. Các Bệnh án (Lần khám)",
            },
        ),
        migrations.CreateModel(
            name="Prescription",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "notes",
                    models.TextField(blank=True, null=True, verbose_name="Dặn dò thêm"),
                ),
                (
                    "encounter",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="prescriptions",
                        to="api.encounter",
                    ),
                ),
            ],
            options={
                "verbose_name": "10. Đơn thuốc",
                "verbose_name_plural": "10. Các Đơn thuốc",
            },
        ),
        migrations.CreateModel(
            name="PrescriptionItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "dosage",
                    models.CharField(
                        max_length=100, verbose_name="Liều lượng/Cách dùng"
                    ),
                ),
                (
                    "quantity",
                    models.PositiveIntegerField(default=1, verbose_name="Số lượng"),
                ),
                (
                    "medicine",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="api.medicine",
                        verbose_name="Thuốc",
                    ),
                ),
                (
                    "prescription",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="api.prescription",
                    ),
                ),
            ],
            options={
                "verbose_name": "11. Chi tiết Đơn thuốc",
                "verbose_name_plural": "11. Các chi tiết Đơn thuốc",
            },
        ),
        migrations.CreateModel(
            name="Service",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200, verbose_name="Tên dịch vụ")),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=0, max_digits=10, verbose_name="Giá dịch vụ"
                    ),
                ),
                (
                    "specialties",
                    models.ManyToManyField(
                        blank=True,
                        related_name="services",
                        to="api.specialty",
                        verbose_name="Thuộc các Chuyên khoa",
                    ),
                ),
            ],
            options={
                "verbose_name": "6. Danh mục Dịch vụ y tế",
                "verbose_name_plural": "6. Các Danh mục Dịch vụ y tế",
            },
        ),
        migrations.CreateModel(
            name="DoctorProfile",
            fields=[
                (
                    "user",
                    models.OneToOneField(
                        limit_choices_to={"role": "DOCTOR"},
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        related_name="doctor_profile",
                        serialize=False,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "license_number",
                    models.CharField(
                        max_length=50, verbose_name="Số giấy phép hành nghề"
                    ),
                ),
                (
                    "bio",
                    models.TextField(
                        blank=True, null=True, verbose_name="Tiểu sử/Giới thiệu"
                    ),
                ),
                (
                    "specialty",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="api.specialty",
                        verbose_name="Chuyên khoa",
                    ),
                ),
            ],
            options={
                "verbose_name": "3. Hồ sơ Chuyên môn Bác sĩ",
                "verbose_name_plural": "3. Các hồ sơ Chuyên môn Bác sĩ",
            },
        ),
        migrations.CreateModel(
            name="RecurringSchedule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "day_of_week",
                    models.IntegerField(
                        choices=[
                            (0, "Thứ Hai"),
                            (1, "Thứ Ba"),
                            (2, "Thứ Tư"),
                            (3, "Thứ Năm"),
                            (4, "Thứ Sáu"),
                            (5, "Thứ Bảy"),
                            (6, "Chủ Nhật"),
                        ],
                        verbose_name="Ngày trong tuần",
                    ),
                ),
                ("start_time", models.TimeField(verbose_name="Giờ bắt đầu")),
                ("end_time", models.TimeField(verbose_name="Giờ kết thúc")),
                (
                    "doctor",
                    models.ForeignKey(
                        limit_choices_to={"role": "DOCTOR"},
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Bác sĩ",
                    ),
                ),
            ],
            options={
                "verbose_name": "7. Lịch làm việc Cố định bác sĩ",
                "verbose_name_plural": "7. Các Lịch làm việc Cố định của bác sĩ",
                "ordering": ["doctor", "day_of_week", "start_time"],
                "unique_together": {("doctor", "day_of_week", "start_time")},
            },
        ),
    ]
