# Generated by Django 5.2.6 on 2025-11-03 08:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="StockTransaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "transaction_type",
                    models.CharField(
                        choices=[
                            ("STOCK_IN", "Nhập kho"),
                            ("STOCK_OUT", "Xuất kho"),
                            ("PRESCRIPTION", "Kê đơn"),
                        ],
                        max_length=20,
                    ),
                ),
                ("quantity", models.IntegerField()),
                (
                    "notes",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="Ghi chú/Lý do",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        limit_choices_to={"role__in": ["ADMIN", "DOCTOR"]},
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "medicine",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="stock_transactions",
                        to="api.medicine",
                    ),
                ),
            ],
            options={
                "verbose_name": "Lịch sử Giao dịch Kho",
                "verbose_name_plural": "Lịch sử Giao dịch Kho",
                "ordering": ["-created_at"],
            },
        ),
    ]
