# Generated by Django 5.2.6 on 2025-11-05 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_stocktransaction"),
    ]

    operations = [
        migrations.AddField(
            model_name="encounter",
            name="services_performed",
            field=models.ManyToManyField(
                blank=True, to="api.service", verbose_name="Các dịch vụ đã thực hiện"
            ),
        ),
    ]
