# Generated by Django 5.2.6 on 2025-11-05 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0003_encounter_services_performed"),
    ]

    operations = [
        migrations.AddField(
            model_name="appointment",
            name="services",
            field=models.ManyToManyField(
                blank=True, to="api.service", verbose_name="Các dịch vụ đăng ký"
            ),
        ),
    ]
