# Generated by Django 5.2.6 on 2025-11-07 08:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0004_appointment_services"),
    ]

    operations = [
        migrations.AlterField(
            model_name="stocktransaction",
            name="transaction_type",
            field=models.CharField(
                choices=[
                    ("VOUCHER_IN", "Nhập theo Phiếu"),
                    ("VOUCHER_OUT", "Xuất theo Phiếu"),
                    ("PRESCRIPTION", "Kê đơn"),
                    ("MANUAL_ADJUST", "Điều chỉnh thủ công"),
                ],
                max_length=20,
            ),
        ),
        migrations.CreateModel(
            name="StockVoucher",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "voucher_type",
                    models.CharField(
                        choices=[
                            ("STOCK_IN", "Phiếu Nhập kho"),
                            ("STOCK_OUT", "Phiếu Xuất kho"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "reason",
                    models.CharField(max_length=255, verbose_name="Lý do/Mô tả"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Phiếu Kho",
                "verbose_name_plural": "Các Phiếu Kho",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddField(
            model_name="stocktransaction",
            name="voucher",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="transactions",
                to="api.stockvoucher",
            ),
        ),
    ]
