# Generated by Django 5.2.6 on 2025-11-07 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0005_alter_stocktransaction_transaction_type_stockvoucher_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="stocktransaction",
            name="voucher",
        ),
        migrations.AlterField(
            model_name="stocktransaction",
            name="transaction_type",
            field=models.CharField(
                choices=[
                    ("STOCK_IN", "Nhập kho"),
                    ("STOCK_OUT", "Xuất kho"),
                    ("PRESCRIPTION", "Kê đơn"),
                ],
                max_length=20,
            ),
        ),
        migrations.DeleteModel(
            name="StockVoucher",
        ),
    ]
